version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.dev
    volumes:
      - ./src:/app
    restart: on-failure
    env_file: .env
    ports:
      - "8080:8080"
  database:
    image: postgres:14.1-alpine
    restart: always
    env_file: .env
    ports:
      - '5433:5432'
    volumes:
      - db:/var/lib/postgresql/data
    depends_on:
      - api
volumes:
  db: {}