FROM python:3.12-slim
ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get install -y \
    netcat-openbsd \
    postgresql-client \
    gcc \
    python3-dev \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY  ./requirements/common.txt /app/

RUN pip install --no-cache-dir -r common.txt \
    && pip install --no-cache-dir gunicorn


COPY ./src/ /app/

EXPOSE 8080

ENV WORKERS=4 \
    LOG_LEVEL=info \
    MODULE_NAME=main \
    VARIABLE_NAME=app \
    PORT=8080

EXPOSE ${PORT}

RUN chmod +x /app/entrypoint.sh

ENTRYPOINT ["sh","/app/entrypoint.sh"]
