FROM python:3.12
ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get install -y \
    binutils \
    libproj-dev

    WORKDIR /app

COPY  ./requirements/common.txt /app/


RUN pip install -r common.txt
RUN pip install -r dev.txt

COPY ./src/ /app/

EXPOSE 8080

RUN chmod +x /app/entrypoint.sh

ENTRYPOINT ["sh","/app/entrypoint.sh"]
